### ISSUE TITLE
Social links aren't visible in Firefox Quantum

### ISSUE THREAD

**Issue by ahmed-taj** [aspittel/aspittel.github.io#3]
I just noticed the social links aren't working properly using the latest Firefox release (not sure about old versions).

Couldn't have much time to investigate it further, but feel free to ask for more info if you need.

## Screenshot

![ali spittel - mozilla firefox_041](https://user-images.githubusercontent.com/12673605/33522820-8cc1a898-d7ff-11e7-997e-111e79d8a13c.png)

## Versions

Browser: Firefox Quantum (57.0.1)
OS: Ubuntu 16.04

Awesome design by the way ;)

**Comment by aspittel** [comment]
Ah thank you! TIL that `preload` attributes don't work in Fire Fox! Great catch! Plus this made me try out Quantum, which is really cool.
