### ISSUE TITLE
Improve letter animation performance by using transform

### ISSUE THREAD

**Issue by wbobeirne** [aspittel/aspittel.github.io#4]
Just read your [blog post](https://zen-of-programming.com/kickass-portfolio/), solid write-up. One thing I noticed while hovering over the letters is they animate one pixel at a time, which makes it looks just a bit choppy when the animation slows down. If you change the following lines https://github.com/aspittel/aspittel.github.io/blob/new-vue/src/components/RainbowLetter.vue#L44 to use transforms instead, e.g. `transform: translateY(50px)` instead of `top: 50px` you'll get sub-pixel rendering and GPU performance instead, which should look a lot smoother.

Keep up the good work 👍

**Comment by aspittel** [comment]
Oh my goodness, thank you so much for this @wbobeirne! Will make that change!!
