### ISSUE TITLE
License and attribution

### ISSUE THREAD

**Issue by trallard** [aspittel/aspittel.github.io#8]
Hi! I love your minimalist site and I would love to make a fork of it. Though I noticed it does not have a license and I'd also love to attribute your work and the effort gone in making this.

**Comment by immortal3** [comment]
@aspittel 
I also love this minimalistic portfolio and want to use it if permission is given by you. 
Can you please update the license of this repo so we can attribute your work?

**Comment by aspittel** [comment]
Hey! I'm not comfortable with people using the code in this repo since I want my portfolio to be unique, but I am working to create some starter portfolios [here](https://github.com/aspittel/portfolio-starters)
